// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // AIzaSyCLCWsYWIG3QDYgV0dH_c7G19PKdr5d06Q
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92Lw0vd32ce6m4J2nBVBWZRYBy4aDB_s',
    appId: '1:408718656984:web:76e9cc7a89e9b4c9d5a8ab',
    messagingSenderId: '408718656984',
    projectId: 'appinjproject',
    authDomain: 'appinjproject.firebaseapp.com',
    storageBucket: 'appinjproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92Lw0vd32ce6m4J2nBVBWZRYBy4aDB_s',
    appId: '1:408718656984:android:1180515e55fb4aab251ead',
    messagingSenderId: '408718656984',
    projectId: 'appinjproject',
    storageBucket: 'appinjproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD92Lw0vd32ce6m4J2nBVBWZRYBy4aDB_s',
    appId:
        '1:408718656984:ios:TO_BE_CONFIGURED', // ⚠️ Please update with real iOS App ID from Firebase Console
    messagingSenderId: '408718656984',
    projectId: 'appinjproject',
    storageBucket: 'appinjproject.firebasestorage.app',
    iosBundleId: 'com.tuktuk.th',
  );
}
