// 77 จังหวัด — code ตรงกับ province_code ใน D1/Go engine
export const PROVINCES = [
  { code: '10', nameTh: 'กรุงเทพมหานคร', nameEn: 'Bangkok' },
  { code: '11', nameTh: 'สมุทรปราการ', nameEn: 'Samut Prakan' },
  { code: '12', nameTh: 'นนทบุรี', nameEn: 'Nonthaburi' },
  { code: '13', nameTh: 'ปทุมธานี', nameEn: 'Pathum Thani' },
  { code: '14', nameTh: 'พระนครศรีอยุธยา', nameEn: 'Ayutthaya' },
  { code: '15', nameTh: 'อ่างทอง', nameEn: 'Ang Thong' },
  { code: '16', nameTh: 'ลพบุรี', nameEn: 'Lopburi' },
  { code: '17', nameTh: 'สิงห์บุรี', nameEn: 'Sing Buri' },
  { code: '18', nameTh: 'ชัยนาท', nameEn: 'Chai Nat' },
  { code: '19', nameTh: 'สระบุรี', nameEn: 'Saraburi' },
  { code: '20', nameTh: 'ชลบุรี', nameEn: 'Chonburi' },
  { code: '21', nameTh: 'ระยอง', nameEn: 'Rayong' },
  { code: '22', nameTh: 'จันทบุรี', nameEn: 'Chanthaburi' },
  { code: '23', nameTh: 'ตราด', nameEn: 'Trat' },
  { code: '24', nameTh: 'ฉะเชิงเทรา', nameEn: 'Chachoengsao' },
  { code: '25', nameTh: 'ปราจีนบุรี', nameEn: 'Prachin Buri' },
  { code: '26', nameTh: 'นครนายก', nameEn: 'Nakhon Nayok' },
  { code: '27', nameTh: 'สระแก้ว', nameEn: 'Sa Kaeo' },
  { code: '30', nameTh: 'นครราชสีมา', nameEn: 'Nakhon Ratchasima' },
  { code: '31', nameTh: 'บุรีรัมย์', nameEn: 'Buri Ram' },
  { code: '32', nameTh: 'สุรินทร์', nameEn: 'Surin' },
  { code: '33', nameTh: 'ศรีสะเกษ', nameEn: 'Si Sa Ket' },
  { code: '34', nameTh: 'อุบลราชธานี', nameEn: 'Ubon Ratchathani' },
  { code: '35', nameTh: 'ยโสธร', nameEn: 'Yasothon' },
  { code: '36', nameTh: 'ชัยภูมิ', nameEn: 'Chaiyaphum' },
  { code: '37', nameTh: 'อำนาจเจริญ', nameEn: 'Amnat Charoen' },
  { code: '38', nameTh: 'บึงกาฬ', nameEn: 'Bueng Kan' },
  { code: '39', nameTh: 'หนองบัวลำภู', nameEn: 'Nong Bua Lam Phu' },
  { code: '40', nameTh: 'ขอนแก่น', nameEn: 'Khon Kaen' },
  { code: '41', nameTh: 'อุดรธานี', nameEn: 'Udon Thani' },
  { code: '42', nameTh: 'เลย', nameEn: 'Loei' },
  { code: '43', nameTh: 'หนองคาย', nameEn: 'Nong Khai' },
  { code: '44', nameTh: 'มหาสารคาม', nameEn: 'Maha Sarakham' },
  { code: '45', nameTh: 'ร้อยเอ็ด', nameEn: 'Roi Et' },
  { code: '46', nameTh: 'กาฬสินธุ์', nameEn: 'Kalasin' },
  { code: '47', nameTh: 'สกลนคร', nameEn: 'Sakon Nakhon' },
  { code: '48', nameTh: 'นครพนม', nameEn: 'Nakhon Phanom' },
  { code: '49', nameTh: 'มุกดาหาร', nameEn: 'Mukdahan' },
  { code: '50', nameTh: 'เชียงใหม่', nameEn: 'Chiang Mai' },
  { code: '51', nameTh: 'ลำพูน', nameEn: 'Lamphun' },
  { code: '52', nameTh: 'ลำปาง', nameEn: 'Lampang' },
  { code: '53', nameTh: 'อุตรดิตถ์', nameEn: 'Uttaradit' },
  { code: '54', nameTh: 'แพร่', nameEn: 'Phrae' },
  { code: '55', nameTh: 'น่าน', nameEn: 'Nan' },
  { code: '56', nameTh: 'พะเยา', nameEn: 'Phayao' },
  { code: '57', nameTh: 'เชียงราย', nameEn: 'Chiang Rai' },
  { code: '58', nameTh: 'แม่ฮ่องสอน', nameEn: 'Mae Hong Son' },
  { code: '60', nameTh: 'นครสวรรค์', nameEn: 'Nakhon Sawan' },
  { code: '61', nameTh: 'อุทัยธานี', nameEn: 'Uthai Thani' },
  { code: '62', nameTh: 'กำแพงเพชร', nameEn: 'Kamphaeng Phet' },
  { code: '63', nameTh: 'ตาก', nameEn: 'Tak' },
  { code: '64', nameTh: 'สุโขทัย', nameEn: 'Sukhothai' },
  { code: '65', nameTh: 'พิษณุโลก', nameEn: 'Phitsanulok' },
  { code: '66', nameTh: 'พิจิตร', nameEn: 'Phichit' },
  { code: '67', nameTh: 'เพชรบูรณ์', nameEn: 'Phetchabun' },
  { code: '70', nameTh: 'ราชบุรี', nameEn: 'Ratchaburi' },
  { code: '71', nameTh: 'กาญจนบุรี', nameEn: 'Kanchanaburi' },
  { code: '72', nameTh: 'สุพรรณบุรี', nameEn: 'Suphan Buri' },
  { code: '73', nameTh: 'นครปฐม', nameEn: 'Nakhon Pathom' },
  { code: '74', nameTh: 'สมุทรสาคร', nameEn: 'Samut Sakhon' },
  { code: '75', nameTh: 'สมุทรสงคราม', nameEn: 'Samut Songkhram' },
  { code: '76', nameTh: 'เพชรบุรี', nameEn: 'Phetchaburi' },
  { code: '77', nameTh: 'ประจวบคีรีขันธ์', nameEn: 'Prachuap Khiri Khan' },
  { code: '80', nameTh: 'นครศรีธรรมราช', nameEn: 'Nakhon Si Thammarat' },
  { code: '81', nameTh: 'กระบี่', nameEn: 'Krabi' },
  { code: '82', nameTh: 'พังงา', nameEn: 'Phang Nga' },
  { code: '83', nameTh: 'ภูเก็ต', nameEn: 'Phuket' },
  { code: '84', nameTh: 'สุราษฎร์ธานี', nameEn: 'Surat Thani' },
  { code: '85', nameTh: 'ระนอง', nameEn: 'Ranong' },
  { code: '86', nameTh: 'ชุมพร', nameEn: 'Chumphon' },
  { code: '90', nameTh: 'สงขลา', nameEn: 'Songkhla' },
  { code: '91', nameTh: 'สตูล', nameEn: 'Satun' },
  { code: '92', nameTh: 'ตรัง', nameEn: 'Trang' },
  { code: '93', nameTh: 'พัทลุง', nameEn: 'Phatthalung' },
  { code: '94', nameTh: 'ปัตตานี', nameEn: 'Pattani' },
  { code: '95', nameTh: 'ยะลา', nameEn: 'Yala' },
  { code: '96', nameTh: 'นราธิวาส', nameEn: 'Narathiwat' },
]
